import Head from 'next/head'
import Image from 'next/image'
import { NextPage } from 'next'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Mike Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      {/* Hero */}

      {/* About */}

      {/* Experience */}

      
      
    </div>
  )
}

export default Home;